import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Info from "../components/Info";
import { ReactNode } from "react";
import "./globals.css";

const quicksand = Quicksand({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Header />
        <div id="detail">
          {children}
        </div>
        <Info />
        <Footer />
      </body>
    </html>
  );
}